BookingRoomHotel/ViewModels/ProfileCustomerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BookingRoomHotel.ViewModels
{
    public class ProfileCustomerViewModel
    {
        [DataType(DataType.Text)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter your name")]
        [StringLength(maximumLength: 30, MinimumLength = 6, ErrorMessage = "Length between 6 - 50")]
        public string Name { get; set; }

        [EmailAddress]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter your email")]
        public string Email { get; set; }

        [Phone]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter your phone")]
        public string Phone { get; set; }

        [DataType(DataType.Date)]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please enter your BirthDay")]
        public DateTime DateOfBirth { get; set; }

        [DataType(DataType.Text)]
        public string Address { get; set; }

        public IFormFile? ImgAvt { get; set; }
        public IFormFile? ImgIdentify1 { get; set; }
        public IFormFile? ImgIdentify2 { get; set; }
    }

    public class ProfileView
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public string ImgAvt { get; set; }
        public string ImgIdentify1 { get; set; }
        public string ImgIdentify2 { get; set; }
        public string Status { get; set; }
    }
}

BookingRoomHotel/Controllers/ProfileCustomerController.cs
using Microsoft.AspNetCore.Mvc;
using BookingRoomHotel.Models;
using System.Data;
using BookingRoomHotel.ViewModels;

namespace BookingRoomHotel.Controllers
{
    public class ProfileCustomerController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IUploadFileService _uploadFileService;

        public ProfileCustomerController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, IUploadFileService uploadFileService)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _uploadFileService = uploadFileService;
        }

        // GET: ProfileCustomer
        public async Task<IActionResult> Index()
        {
            var CustomerId = HttpContext.Session.GetString("CustomerId");
            var Customer = await _context.Customers.FindAsync(CustomerId);
            return (Customer == null) ?
                RedirectToAction("Error","Home") : View(CustomerToProfileView(Customer));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(ProfileCustomerViewModel model)
        {
            var CustomerId = HttpContext.Session.GetString("CustomerId");
            var CustomertoUpdate = await _context.Customers.FindAsync(CustomerId);

            if (ModelState.IsValid)
            {
                string profileFileName = _uploadFileService.uploadImage(model.ImgAvt, "images/customer/profile");
                string imgidentify1 = _uploadFileService.uploadImage(model.ImgIdentify1, "images/customer/imgIdentify1");
                string imgidentify2 = _uploadFileService.uploadImage(model.ImgIdentify2, "images/customer/imgIdentify2");
                CustomertoUpdate.Name = model.Name;
                CustomertoUpdate.Email = model.Email;
                CustomertoUpdate.Phone = model.Phone;
                CustomertoUpdate.Address = model.Address;
                CustomertoUpdate.DateOfBirth = model.DateOfBirth;
                CustomertoUpdate.ImgAvt = profileFileName == null? CustomertoUpdate.ImgAvt: profileFileName;
                CustomertoUpdate.ImgIdentify1 = imgidentify1 == null ? CustomertoUpdate.ImgIdentify1 : imgidentify1;
                CustomertoUpdate.ImgIdentify2 = imgidentify2 == null ? CustomertoUpdate.ImgIdentify2 : imgidentify2;
                _context.Customers.Update(CustomertoUpdate);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            
            return View(CustomerToProfileView(CustomertoUpdate));
        }

        private ProfileView CustomerToProfileView(Customer Customer)
        {
            ProfileView cus = new ProfileView();
            cus.Name = Customer.Name;
            cus.Email = Customer.Email;
            cus.Phone = Customer.Phone;
            cus.Address = Customer.Address;
            cus.DateOfBirth = Customer.DateOfBirth;
            cus.ImgAvt = Customer.ImgAvt;
            cus.ImgIdentify1 = Customer.ImgIdentify1;
            cus.ImgIdentify2 = Customer.ImgIdentify2;
            cus.Status = Customer.Status;
            return cus;
        }

    }
}

BookingRoomHotel/Views/ProfileCustomer/Index.cshtml
@model BookingRoomHotel.ViewModels.ProfileView

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile user</title>
    <link href="https://fonts.googleapis.com/css2?family=Merienda:wght@400;700&family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/assets/css/style.css" />
    <style>
        * {
            font-family: 'Poppins', sans-serif;
        }

        .h-font {
            font-family: 'Merienda', cursive;
        }

        body {
            margin-top: 20px;
            background-color: #f2f6fc;
            color: #69707a;
        }

        .img-account-profile {
            height: 10rem;
        }

        .rounded-circle {
            border-radius: 50% !important;
        }

        .card {
            box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
        }

            .card .card-header {
                font-weight: 500;
            }

        .card-header:first-child {
            border-radius: 0.35rem 0.35rem 0 0;
        }

        .card-header {
            padding: 1rem 1.35rem;
            margin-bottom: 0;
            background-color: rgba(33, 40, 50, 0.03);
            border-bottom: 1px solid rgba(33, 40, 50, 0.125);
        }

        .form-control, .dataTable-input {
            display: block;
            width: 100%;
            padding: 0.875rem 1.125rem;
            font-size: 0.875rem;
            font-weight: 400;
            line-height: 1;
            color: #69707a;
            background-color: #fff;
            background-clip: padding-box;
            border: 1px solid #c5ccd6;
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
            border-radius: 0.35rem;
            transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
        }

        .nav-borders .nav-link.active {
            color: #0061f2;
            border-bottom-color: #0061f2;
        }

        .nav-borders .nav-link {
            color: #69707a;
            border-bottom-width: 0.125rem;
            border-bottom-style: solid;
            border-bottom-color: transparent;
            padding-top: 0.5rem;
            padding-bottom: 0.5rem;
            padding-left: 0;
            padding-right: 0;
            margin-left: 1rem;
            margin-right: 1rem;
        }
    </style>
</head>

<body>

    <div class="container-xl px-4 mt-4">
        <nav class="nav nav-borders">
            <a class="nav-link active ms-0" href="https://www.bootdey.com/snippets/view/bs5-edit-profile-account-details" target="__blank">Profile</a>
        </nav>
        <hr class="mt-0 mb-4">
        <div class="row">

            <div class="col-xl-12">

                <div class="card mb-4">
                    <div class="card-header">Account Details</div>
                    <div class="card-body">
                        <form method="post" asp-action="Index" asp-controller="ProfileCustomer" enctype="multipart/form-data">
                            <div class="card mb-4 mb-xl-0">
                                <div class="card-header">Profile Picture</div>

                                <div class="card-body text-center upload-btn-wrapper">
                                    <img class="img-account-profile rounded-circle mb-2" height="140" width="140" src="~/images/customer/profile/@Model.ImgAvt">
                                    <div class="small font-italic text-muted mb-4">JPG or PNG no larger than 5 MB</div>
                                    <button class="btn btn-primary" type="button" id="uploadButton">Upload new image</button>
                                    <input type="file" id="fileInput" style="display: none;" asp-for="ImgAvt" accept="image/*">
                                </div>

                            </div>
                            <div class="mt-3 mb-3">
                                <label class="small mb-1" for="inputUsername">Username</label>@if (@Model.Status.Equals("Active"))
                                {
                                    <span class="badge badge-pill bg-success-light" asp-for="Status">@Model.Status</span>
                                }
                                else
                                {
                                    <span class="badge badge-pill bg-danger-light" asp-for="Status">@Model.Status</span>
                                }
                                <input class="form-control" asp-for="Name" type="text" placeholder="Enter your username" value="@Model.Name">

                            </div>

                            <div class="mb-3">
                                <label class="small mb-1" for="inputEmailAddress">Gmail</label>
                                <input class="form-control" asp-for="Email" type="email" placeholder="Enter your email address" value="@Model.Email">
                            </div>

                            <div class="mb-3">
                                <label class="small mb-1" for="inputEmailAddress">Address</label>
                                <input class="form-control" asp-for="Address" type="text" placeholder="Enter your email address" value="@Model.Address">
                            </div>

                            <div class="row gx-3 mb-3">
                                <div class="col-md-6">
                                    <label class="form-label">Phone number</label>
                                    <input type="number" asp-for="Phone" class="form-control shadow-none" value="@Model.Phone">
                                </div>

                                <div class="col-md-6">
                                    <label class="form-label">Date of birth</label>
                                    <input type="date" asp-for="DateOfBirth" class="form-control shadow-none" value="@Model.DateOfBirth.ToString("yyyy-MM-dd")">
                                </div>
                            </div>

                            <div class="row gx-3 mb-3">
                                <div class="col-md-6">
                                    <label class="card-title">Picture Identify 1</label>
                                    <div class="d-flex justify-content-center mb-2" width="100" height="160">
                                        <img class="img-account-profile" src="~/images/customer/imgIdentify1/@Model.ImgIdentify1">
                                    </div>
                                    <input type="file" asp-for="ImgIdentify1" class="form-control shadow-none" accept="image/*">
                                </div>
                                <div class="col-md-6">
                                    <label class="card-title">Picture Identify 2</label>
                                    <div class="d-flex justify-content-center mb-2" width="100" height="160">
                                        <img class="img-account-profile" src="~/images/customer/imgIdentify2/@Model.ImgIdentify2">
                                    </div>
                                    <input type="file" asp-for="ImgIdentify2" class="form-control shadow-none" accept="image/*">
                                </div>

                            </div>
                            <button class="btn btn-primary" type="submit">Save changes</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--Footer-->
    <div class="container-fluid bg-white mt-5">
        <div class="row">
            <div class="col-lg-4 mt-4">
                <h3 class="h-font fw-bold fs-3 mb-2">KIOT HOTEL</h3>
                <p>
                    Kiot Hotel was established in September 2023, with CEOs in King Of Loser team.
                    With the goal of always making customers happy and building trust in the first place, we will always bring you services, providing excellent experience in this place.
                </p>
            </div>

            <div class="col-lg-4 mt-4">
                <h5 class="mb-3">Links</h5>
                <a href="" class="d-inline-block mb-2 text-dark text-decoration-none"> Home </a> <br>
                <a href="" class="d-inline-block mb-2 text-dark text-decoration-none"> Rooms </a> <br>
                <a href="" class="d-inline-block mb-2 text-dark text-decoration-none"> Facilities </a> <br>
                <a href="" class="d-inline-block mb-2 text-dark text-decoration-none"> Contact us </a> <br>
                <a href="" class="d-inline-block mb-2 text-dark text-decoration-none"> About </a>
            </div>

            <div class="col-lg-4 mt-4">
                <h5 class="mb-3">Follow us</h5>
                <a href="" class="d-inline-block text-dark text-decoration-none mb-2"> <i class="bi bi-envelope"></i> Gmail</a><br>
                <a href="" class="d-inline-block text-dark text-decoration-none mb-2"> <i class="bi bi-facebook"></i> Facebook</a><br>
                <a href="" class="d-inline-block text-dark text-decoration-none mb-2"> <i class="bi bi-twitter"></i> Twitter</a><br>
                <a href="" class="d-inline-block text-dark text-decoration-none mb-2"> <i class="bi bi-instagram"></i> Instagram</a><br>
            </div>
        </div>
    </div>
    <h6 class="text-center bg-dark text-white p-3 m-0">Developed by KING OF LOSER TEAM - FPTU - SE17B.NET</h6>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            document.getElementById('uploadButton').addEventListener('click', function () {
                document.getElementById('fileInput').click();
            });
        });
    </script>


    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.stellar.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.magnific-popup.min.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/bootstrap-datepicker.js"></script>
    <script src="~/js/scrollax.min.js"></script>
    <script src="~/js/main.js"></script>
</body>
</html>